# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-4-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-4-2
pod "PGFramework"
  target 'Test-4-2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-4-2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
